---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: webinar-docs-site-build
spec:
  description: >-
    Pipeline to build the website and deploy it
  params:
    - name: git-url
      type: string
      description: URL to git repository
      default: https://github.com/hupiper/webinar-site.git
    - name: git-revision
      type: string
      description: Git revision (e.g. tag/branch/sha) to checkout
      default: main
  workspaces:
    - name: webinar-code
  tasks:
    - name: git-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.git-revision)"
      workspaces:
        - name: output
          workspace: webinar-code
    - name: build
      taskRef:
        kind: ClusterTask
        name: build-buildconfig
      params:
        - name: template-file-path
          value: devops/build-config-template.yaml
        - name: build-name
          value: webinar-website
        - name: process-args
          value: >-
            -p NAME=webinar-website
            -p TAG="$(params.git-revision)"
        - name: follow-build-args
          value: >-
            --from-dir="/workspace/source"
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: webinar-code
    - name: deploy
      taskRef:
        kind: ClusterTask
        name: openshift-deploy-v1-1-0
      params:
        - name: template-file-path
          value: devops/deploy-template.yaml
        - name: resource-kind
          value: deployment
        - name: resource-name
          value: webinar-site
        - name: always-rollout
          value: "true"
        - name: timeout
          value: 4m
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: webinar-code

